#! /bin/sh


start() {
	printf "Starting app: "
	( cd /root; ./run )&
	echo "done"
}


stop() {
	printf "Stopping input-event-daemon: "
	killall run
	echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
